// <auto-generated />
using System;
using ComfortProfilesSharing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComfortProfilesSharing.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181030200301_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComfortProfilesSharing.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.ChairType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("ChairTypes");

                    b.HasData(
                        new { Id = 1, Name = "Type1" },
                        new { Id = 2, Name = "Type2" },
                        new { Id = 3, Name = "Type3" },
                        new { Id = 4, Name = "Not Selected" }
                    );
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.ClimatLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AirHumidity");

                    b.Property<DateTime>("Date");

                    b.Property<int>("HowOftenId");

                    b.Property<bool?>("IsRepeatable");

                    b.Property<Guid>("RoomId");

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.HasIndex("HowOftenId");

                    b.HasIndex("RoomId");

                    b.ToTable("ClimatLogs");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.CoffeeDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<int>("CurrentCoffeeAmount");

                    b.Property<int>("CurrentMilkAmount");

                    b.Property<int>("CurrentWaterAmount");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique()
                        .HasFilter("[AppUserId] IS NOT NULL");

                    b.ToTable("CoffeDevices");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.CoffeeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CoffeeDeviceId");

                    b.Property<Guid>("CoffeeTypeId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("HowOftenId");

                    b.Property<bool?>("IsRepeatable");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeDeviceId");

                    b.HasIndex("CoffeeTypeId");

                    b.HasIndex("HowOftenId");

                    b.ToTable("CoffeeLogs");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.CoffeeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CoffeeTypes");

                    b.HasData(
                        new { Id = new Guid("8abe1178-fee2-49a6-952a-1d8d338bbb49"), Name = "Americano" },
                        new { Id = new Guid("e872aef3-36b7-48dd-8871-19289e69b145"), Name = "Latte" },
                        new { Id = new Guid("cfc7d85e-3515-4939-b9c3-d47eba7cb5b5"), Name = "Cappuccino" },
                        new { Id = new Guid("94a7a25c-4be6-4182-8485-c4279a97cb53"), Name = "Espresso" },
                        new { Id = new Guid("beb2a177-dea9-455a-884e-83f19d8d05c7"), Name = "Macchiato" },
                        new { Id = new Guid("97529393-b5fa-44c0-a588-7815973634e3"), Name = "Mochaccino" },
                        new { Id = new Guid("b8898be2-8bad-4afd-99b2-a928b4619b3f"), Name = "Flat White" },
                        new { Id = new Guid("76913715-09ec-42f7-b53a-4e97dc59e255"), Name = "Vienna" }
                    );
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.HowOften", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Explanation");

                    b.HasKey("Id");

                    b.ToTable("HowOftens");

                    b.HasData(
                        new { Id = 1, Explanation = "Never" },
                        new { Id = 2, Explanation = "Every Day" },
                        new { Id = 3, Explanation = "Every Monday" },
                        new { Id = 4, Explanation = "Every Tuesday" },
                        new { Id = 5, Explanation = "Every Wednesday" },
                        new { Id = 6, Explanation = "Every Thursday" },
                        new { Id = 7, Explanation = "Every Friday" },
                        new { Id = 8, Explanation = "Every Saturday" },
                        new { Id = 9, Explanation = "Every Sunday" },
                        new { Id = 10, Explanation = "Every Weekday" },
                        new { Id = 11, Explanation = "Every Weekend" }
                    );
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.IlluminationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("HowOftenId");

                    b.Property<bool>("IsLight");

                    b.Property<bool?>("IsRepeatable");

                    b.Property<int>("LightIntensity");

                    b.Property<Guid>("RoomId");

                    b.HasKey("Id");

                    b.HasIndex("HowOftenId");

                    b.HasIndex("RoomId");

                    b.ToTable("IlluminationLogs");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.MattressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("MattressTypes");

                    b.HasData(
                        new { Id = 1, Name = "Type1" },
                        new { Id = 2, Name = "Type2" },
                        new { Id = 3, Name = "Type3" },
                        new { Id = 4, Name = "Not Selected" }
                    );
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<int>("CurrentAirHumidity");

                    b.Property<bool>("CurrentIsLight");

                    b.Property<int>("CurrentLightIntensity");

                    b.Property<int>("CurrentTemperature");

                    b.Property<string>("Name");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.StaticInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Allergens");

                    b.Property<string>("AppUserId");

                    b.Property<int>("ChairTypeId");

                    b.Property<int>("ClothingSize");

                    b.Property<string>("FruitPreferences");

                    b.Property<string>("KindOfCoffee");

                    b.Property<string>("KindOfTea");

                    b.Property<int>("MattressTypeId");

                    b.Property<string>("MusicalPreferences");

                    b.Property<int>("ShoeSize");

                    b.Property<int>("TableTypeId");

                    b.Property<int>("WaterTypeId");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique()
                        .HasFilter("[AppUserId] IS NOT NULL");

                    b.HasIndex("ChairTypeId");

                    b.HasIndex("MattressTypeId");

                    b.HasIndex("TableTypeId");

                    b.HasIndex("WaterTypeId");

                    b.ToTable("StaticInfos");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.TableType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("TableTypes");

                    b.HasData(
                        new { Id = 1, Name = "Type1" },
                        new { Id = 2, Name = "Type2" },
                        new { Id = 3, Name = "Type3" },
                        new { Id = 4, Name = "Not Selected" }
                    );
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.Teapot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppUserId");

                    b.Property<int>("ComfortTemperature");

                    b.Property<int>("CurrentTemperature");

                    b.Property<int>("CurrentWaterAmount");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique()
                        .HasFilter("[AppUserId] IS NOT NULL");

                    b.ToTable("Teapots");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.TeapotLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("HowOftenId");

                    b.Property<bool?>("IsRepeatable");

                    b.Property<Guid>("TeapotId");

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.HasIndex("HowOftenId");

                    b.HasIndex("TeapotId");

                    b.ToTable("TeapotLogs");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.WaterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("WaterTypes");

                    b.HasData(
                        new { Id = 1, Name = "Carbonated" },
                        new { Id = 2, Name = "Not carbonated" },
                        new { Id = 4, Name = "Not Selected" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.ClimatLog", b =>
                {
                    b.HasOne("ComfortProfilesSharing.Models.HowOften", "HowOften")
                        .WithMany("ClimatLogs")
                        .HasForeignKey("HowOftenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComfortProfilesSharing.Models.Room", "Room")
                        .WithMany("ClimatLogs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.CoffeeDevice", b =>
                {
                    b.HasOne("ComfortProfilesSharing.Models.AppUser", "AppUser")
                        .WithOne("CoffeDevice")
                        .HasForeignKey("ComfortProfilesSharing.Models.CoffeeDevice", "AppUserId");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.CoffeeLog", b =>
                {
                    b.HasOne("ComfortProfilesSharing.Models.CoffeeDevice", "CoffeeDevice")
                        .WithMany("CoffeeLogs")
                        .HasForeignKey("CoffeeDeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComfortProfilesSharing.Models.CoffeeType", "CoffeeType")
                        .WithMany("CoffeLogs")
                        .HasForeignKey("CoffeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComfortProfilesSharing.Models.HowOften", "HowOften")
                        .WithMany("CoffeeLogs")
                        .HasForeignKey("HowOftenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.IlluminationLog", b =>
                {
                    b.HasOne("ComfortProfilesSharing.Models.HowOften", "HowOften")
                        .WithMany("IlluminationLogs")
                        .HasForeignKey("HowOftenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComfortProfilesSharing.Models.Room", "Room")
                        .WithMany("IlluminationLogs")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.Room", b =>
                {
                    b.HasOne("ComfortProfilesSharing.Models.AppUser", "AppUser")
                        .WithMany("Rooms")
                        .HasForeignKey("AppUserId");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.StaticInfo", b =>
                {
                    b.HasOne("ComfortProfilesSharing.Models.AppUser", "AppUser")
                        .WithOne("StaticInfo")
                        .HasForeignKey("ComfortProfilesSharing.Models.StaticInfo", "AppUserId");

                    b.HasOne("ComfortProfilesSharing.Models.ChairType", "ChairType")
                        .WithMany("StaticInfos")
                        .HasForeignKey("ChairTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComfortProfilesSharing.Models.MattressType", "MattressType")
                        .WithMany("StaticInfos")
                        .HasForeignKey("MattressTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComfortProfilesSharing.Models.TableType", "TableType")
                        .WithMany("StaticInfos")
                        .HasForeignKey("TableTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComfortProfilesSharing.Models.WaterType", "WaterType")
                        .WithMany("StaticInfos")
                        .HasForeignKey("WaterTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.Teapot", b =>
                {
                    b.HasOne("ComfortProfilesSharing.Models.AppUser", "AppUser")
                        .WithOne("Teapot")
                        .HasForeignKey("ComfortProfilesSharing.Models.Teapot", "AppUserId");
                });

            modelBuilder.Entity("ComfortProfilesSharing.Models.TeapotLog", b =>
                {
                    b.HasOne("ComfortProfilesSharing.Models.HowOften", "HowOften")
                        .WithMany("TeapotLogs")
                        .HasForeignKey("HowOftenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ComfortProfilesSharing.Models.Teapot", "Teapot")
                        .WithMany("TeapotLogs")
                        .HasForeignKey("TeapotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
